image: node:16.5.0

stages:
  - build
  - deploy

variables:
  SOURCEMAP_BASE_URL: https://lucidac-gui.anabrid.dev/main/

default:
  cache:
    key:
      files:
        - package-lock.json
      prefix: npm
    paths:
      - node_modules/

build_headless:
  stage: build
  script:
    - npm install
    - HEADLESS_BUILD=true npm run build
    - cp *.md dist/
  artifacts:
    paths:
      - dist

build_for_teensy:
  stage: build
  script:
    - npm install
    - npm run build
    - cp *.md dist/
  artifacts:
    paths:
      - dist

upload_headless_to_webserver:
  stage: deploy
  image: svenk/latex
  needs:
    - build_headless
  script:
    - chmod 600 "$SSH_PRIVATE_KEY_FILE_STAGING"
    - echo "ai.svenk.org ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBE2YTwpWWq4ceRXHbCFHlw5kmRVLQjKbdYeFAAyYUDXFRhCjRknE6DKlGIIciKOqzAMiFGz5/vxb6tKMCKBeFU0=" > ~/userknown.txt
    - echo -e "cd anabrid.dev/lucidac-gui/main/\nput -R dist/*" | sftp -o "UserKnownHostsFile=~/userknown.txt" -i"$SSH_PRIVATE_KEY_FILE_STAGING" $DEPLOY_STAGING_SSH_HOST

